# -*- coding: utf-8 -*-
"""POO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvofKkRMNzUWpNLWZTneNRbops8EOzV8
"""

class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def mostrar(self):
        print(f"{self.nombre}: {self.edad} años")


class Familia:
    def __init__(self, edad_juan):
        self.juan = Persona("Juan", edad_juan)
        self.alberto = Persona("Alberto", (2/3) * edad_juan)
        self.ana = Persona("Ana", (4/3) * edad_juan)
        edad_mama = self.juan.edad + self.alberto.edad + self.ana.edad
        self.mama = Persona("Mamá", edad_mama)

    def mostrar_edades(self):
        self.mama.mostrar()
        self.juan.mostrar()
        self.alberto.mostrar()
        self.ana.mostrar()

edad_juan = float(input("Ingrese la edad de Juan: "))
familia = Familia(edad_juan)
familia.mostrar_edades()

class SeguimientoAlgoritmo:
    def __init__(self):
        self.suma = 0
        self.x = 0
        self.y = 0

    def ejecutar(self):
        print("--- Seguimiento del algoritmo ---")

        self.suma = 0
        print(f"SUMA = {self.suma}")

        self.x = 20
        print(f"X = {self.x}")

        self.suma = self.suma + self.x
        print(f"SUMA = SUMA + X  ->  SUMA = {self.suma}")

        self.y = 40
        print(f"Y = {self.y}")

        self.x = self.x + self.y ** 2
        print(f"X = X + Y ** 2  ->  X = {self.x}")

        self.suma = self.suma + self.x / self.y
        print(f"SUMA = SUMA + X / Y  ->  SUMA = {self.suma}")

        print(f"\nEL VALOR DE LA SUMA ES: {self.suma}")

algoritmo = SeguimientoAlgoritmo()
algoritmo.ejecutar()

class Empleado:
    def __init__(self, horas_trabajadas, valor_hora):
        self.horas_trabajadas = horas_trabajadas
        self.valor_hora = valor_hora
        self.salario_bruto = 0
        self.retencion = 0
        self.salario_neto = 0

    def calcular_salario(self):
        self.salario_bruto = self.horas_trabajadas * self.valor_hora
        self.retencion = self.salario_bruto * 0.125
        self.salario_neto = self.salario_bruto - self.retencion

    def mostrar_resultados(self):
        print(f"Salario bruto: ${self.salario_bruto:,.2f}")
        print(f"Retención en la fuente: ${self.retencion:,.2f}")
        print(f"Salario neto: ${self.salario_neto:,.2f}")

horas = float(input("Ingrese las horas trabajadas: "))
valor_hora = float(input("Ingrese el valor por hora: "))

empleado = Empleado(horas, valor_hora)
empleado.calcular_salario()
empleado.mostrar_resultados()

class Numero:
    def __init__(self, valor):
        self.valor = valor
        self.cuadrado = 0
        self.cubo = 0

    def calcular_potencias(self):
        self.cuadrado = self.valor ** 2
        self.cubo = self.valor ** 3

    def mostrar_resultados(self):
        print(f"Número: {self.valor}")
        print(f"Cuadrado: {self.cuadrado}")
        print(f"Cubo: {self.cubo}")

num = float(input("Ingrese un número: "))

numero = Numero(num)
numero.calcular_potencias()
numero.mostrar_resultados()

import math

class Circulo:
    def __init__(self, radio):
        self.radio = radio
        self.area = 0
        self.longitud_circunferencia = 0

    def calcular(self):
        self.area = math.pi * self.radio ** 2
        self.longitud_circunferencia = 2 * math.pi * self.radio

    def mostrar_resultados(self):
        print(f"Radio: {self.radio}")
        print(f"Área: {self.area:.2f}")
        print(f"Longitud de la circunferencia: {self.longitud_circunferencia:.2f}")


radio = float(input("Ingrese el radio del círculo: "))

circulo = Circulo(radio)
circulo.calcular()
circulo.mostrar_resultados()